# Generated by Django 4.2.30 on 2026-09-02 10:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_profildesa_sosmed_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KelompokTani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Kelompok Tani Suka Maju', max_length=200)),
                ('kategori', models.CharField(choices=[('wanita', 'Kelompok Tani Wanita'), ('pria', 'Kelompok Tani Pria')], max_length=50)),
                ('ketua', models.CharField(blank=True, max_length=150)),
                ('jumlah_anggota', models.PositiveIntegerField(blank=True, default=0)),
                ('deskripsi', tinymce.models.HTMLField(blank=True, help_text='Penjelasan singkat tentang kelompok tani ini')),
                ('foto_utama', models.ImageField(blank=True, null=True, upload_to='kelompok_tani/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Tampilkan di Website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kelompok Tani',
                'verbose_name_plural': 'Kelompok Tani',
                'ordering': ['kategori', 'nama'],
            },
        ),
    ]
